### ISSUE TITLE
bug in doubletFinder code when reuse.pANN not FALSE

### ISSUE THREAD

**Issue by jdrnevich** [chris-mcginnis-ucsf/DoubletFinder#220]
I just installed DoubletFinder today (v2.0.4) and I was trying to walk through the Example codes show on the README (https://github.com/chris-mcginnis-ucsf/DoubletFinder?tab=readme-ov-file#example-code-for-real-world-applications) on my own data, and was fine until this part:

```
seu_kidney <- doubletFinder(seu_kidney, PCs = 1:10, pN = 0.25, pK = 0.09, nExp = nExp_poi.adj, reuse.pANN = "pANN_0.25_0.09_913", sct = FALSE)
Error in if (reuse.pANN) { : argument is not interpretable as logical
```

I tried debugging and the error is in the very first line of code where it expects `reuse.pANN` to either be `TRUE/FALSE`, not a character vector or `FALSE`:
```
debug: {
    if (reuse.pANN) {
        pANN.old <- seu@meta.data[, reuse.pANN]
        classifications <- rep("Singlet", length(pANN.old))
        classifications[order(pANN.old, decreasing = TRUE)[1:nExp]] <- "Doublet"
        seu@meta.data[, paste("DF.classifications", pN, pK, nExp, 
            sep = "_")] <- classifications
        return(seu)
    }
```

There are several ways to fix this but I'm not sure what approach you'd prefer so I didn't submit a pull request. 

Thanks!

**Comment by danhtruong** [comment]
I am getting the same error.

**Comment by bingqiWu** [comment]
I met the same error :(

**Comment by FloraWinston** [comment]
I got the same error hh

**Comment by Yasminelhajj** [comment]
I am also getting the same error

**Comment by xristosfp3** [comment]
I am also getting the same error. Any solutions to this?

**Comment by Jyng321** [comment]
Hi all,
I had a look at the source code here: https://github.com/chris-mcginnis-ucsf/DoubletFinder/blob/master/R/doubletFinder.R.
I tried to do that manually and it worked.

```
pN <- 0.25
pK <- 0.01
nExp <- nExp_poi.adj
reuse.pANN <- "pANN_0.25_0.01_2364"
pANN.old <- mGlio_max@meta.data[ , reuse.pANN]
classifications <- rep("Singlet", length(pANN.old))
classifications[order(pANN.old, decreasing=TRUE)[1:nExp]] <- "Doublet"
obj@meta.data[, paste("DF.classifications",pN,pK,nExp,sep="_")] <- classifications
```

I hope it can help.
Jyng.

**Comment by haibol2016** [comment]
@jdrnevich, the bug should have been fixed.

**Comment by jdrnevich** [comment]
Thanks! I'm starting spring break tomorrow so I'm not sure when I will test it out

**Comment by AnaHowellsFerreira** [comment]
Hi dev team, 
I think the error is still there. It seems like it's a type on line 69 that is crashing it. I didn't want to submit a pull request, but the "is.NULL" should be "is.null". 

Thanks!

**Comment by haibol2016** [comment]
Oh. That's a typo. I just corrected it.  Thank you.

Haibo

**Comment by JackieMium** [comment]
Hi I am still getting errors here I think. Checking the code starting from line 69 here:

```
  if (is.null(reuse.pANN)) {
    pANN.old <- seu@meta.data[ , reuse.pANN]
    classifications <- rep("Singlet", length(pANN.old))
    classifications[order(pANN.old, decreasing=TRUE)[1:nExp]] <- "Doublet"
    seu@meta.data[, paste("DF.classifications",pN,pK,nExp,sep="_")] <- classifications
    return(seu)
```


when `is.null(reuse.pANN)` is `TRUE` the loop in question is executed and the next line

```
pANN.old <- seu@meta.data[ , reuse.pANN]
```

does not make sense since `reuse.pANN` is already `NULL`, we are running `pANN.old <- seu@meta.data[ , NULL]` which returns nothing.

**Comment by haibol2016** [comment]
Sorry about that.  I should have changed  `if (is.null(reuse.pANN))` to `if (!is.null(reuse.pANN))`.  I should be more careful.

**Comment by haibol2016** [comment]
@JackieMium, what's the benefit to use the "reuse.pANN" argument?

**Comment by JackieMium** [comment]
> [@JackieMium](https://github.com/JackieMium), what's the benefit to use the "reuse.pANN" argument?

If you read `paramSweep.R` and `parallel_paramSweep.R` you will see that we are finding reasonale `nExp` and `pK` values, which utilizes `pANN`. If the user passes a non-NULL `reuse.pANN` argument, then we assume pre-calculated `pANN` in `meta.data` should be used instead.

**Comment by chris-mcginnis-ucsf** [comment]
This is all making me reconsider how useful the reuse.pANN argument is at all in the base doubletFinder function -- it essentially just re-thresholds the pANN vector already present in the metadata according to an adjusted expected number of doublets... very easy to do manually. Could think about removing and (perhaps) adding a new function to redo the thresholding -- @haibol2016 thoughts?
